export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const AGREGAR_CARRITO = "AGREGAR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
export const ELIMINAR_TODO_CARRITO = "ELIMINAR_TODO_CARRITO";
export const CAMBIAR_COLOR = "CAMBIAR_COLOR";
export const VENTA = "VENTA";